//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gunter.roy.codeproject.entitydatamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public decimal ID { get; set; }
        public decimal UserID { get; set; }
        public string Command1 { get; set; }
    }
}
